### ISSUE TITLE
add a 'check for updates' step to the 'check installation prereqs' step

### ISSUE THREAD

**Issue by gamerson** [gamerson/liferay-ide#4151]
See code here: https://github.com/gamerson/liferay-ide-ee/blob/master/studio/plugins/com.liferay.studio.product.ui/src/com/liferay/studio/product/ui/StudioUpdateJob.java

For how to perform an update to a specified repository.

**Comment by jtydhr88** [comment]
we will do it in markdown and generate steps automatically
