### ISSUE TITLE
Actions on upgrade problems in Project Explorer should provide actions that were in previous upgrade tool 

### ISSUE THREAD

**Issue by gamerson** [gamerson/liferay-ide#4164]
- [ ] Mark as resolve
- [ ] Mark as ignore
- [ ] Fix automatically
... everything else that was in previous tool

**Comment by gamerson** [comment]
[ ] Mark as resolve
[ ] Mark as ignore
[ ] Fix automatically
... everything else that was in previous tool

**Comment by jtydhr88** [comment]
hey @Seiphon, can you take a look at it? thanks
