### ISSUE TITLE
When user clicks on any step item area in the TasksViewer it should activate the “Plan Info View”

### ISSUE THREAD

**Issue by jtydhr88** [gamerson/liferay-ide#4178]

**Comment by jtydhr88** [comment]
I'd like to make it simple to implement, just add one action to allow user show the upgrade info view manually when it missing, because auto-active every time may not has a good user experience, they may want to focus on somewhere else or not turn to this view.
do it in here https://github.com/gamerson/liferay-ide/pull/4288

**Comment by gamerson** [comment]
This is now merged in https://github.com/gamerson/liferay-ide/commit/2f67eaf9856d3ef1b37b031c7247c0bed7a6e328

Thanks Terry
