### ISSUE TITLE
Better to align Restart and Skip hyperlink left instead of indent more on step which has substeps

### ISSUE THREAD

**Issue by yanan** [gamerson/liferay-ide#4252]
Expected:
Prepare for Upgrade
[Restart]()
[Skip]()

Actual now:
![align](https://user-images.githubusercontent.com/1308942/55533418-cab5fc80-56e3-11e9-89b2-108f652d9bf0.png)

**Comment by simonjhy** [comment]
Finished(9fa703b9dabde5ffc612d93fd7f9ce73bce79405)
