### ISSUE TITLE
watch BLADE-423

### ISSUE THREAD

**Issue by jtydhr88** [gamerson/liferay-ide#4290]

**Comment by jtydhr88** [comment]
https://issues.liferay.com/browse/BLADE-423

**Comment by simonjhy** [comment]
Hi greg, I sent https://github.com/gamerson/liferay-blade-cli/pull/835 for this issue.

**Comment by simonjhy** [comment]
it has been merged, see this https://github.com/gamerson/liferay-blade-cli/pull/836

**Comment by yanan** [comment]
Need to be fixed: https://issues.liferay.com/browse/BLADE-442
