### ISSUE TITLE
Auto-Correct Upgrade Problems will remove Liferay Upgrade Problems which in Project Explorer

### ISSUE THREAD

**Issue by yanan** [gamerson/liferay-ide#4297]
- click Skip on Auto-Correct Upgrade Problems
- click Find Upgrade Problems, notice Liferay Upgrade Problems in Project Explorer
- Restart and Perform Auto-Correct Upgrade Problems
notice "Liferay Upgrade Problems" will be removed

**Comment by jtydhr88** [comment]
it should be an issue, after you auto-correct, it should remove the previous results and you need to perform Find upgrade problems by yourself to re-find.
